on:
  push:
    # runs tests for commits pushed to master
    branches:
      - master
    # do not run tests if file README.md changes
    paths-ignore:
      - 'README.md'
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
    run_tests:
        runs-on: self-hosted
        steps:
        # checkout code from a repository
        - uses: actions/checkout@v2


